// Original listening scripts, read aloud in-app via the Web Speech API to
// simulate the 4 IELTS Listening sections. Each has comprehension questions.

export const LISTENING_SCRIPTS = [
  {
    id: 'ls-1',
    section: 1,
    title: 'Booking a Hotel Room',
    type: 'Everyday conversation',
    text: `Good morning, Lakeside Hotel, how can I help you? Hi, I'd like to book a room for two nights, arriving on the twelfth of March. Sure, let me check availability. Would you like a single or a double room? A double room, please, with a view of the lake if possible. Of course. That would be room type Deluxe Lake View, and the rate is one hundred and forty dollars per night. Would you like breakfast included? Yes, please add breakfast. That brings the total to three hundred and forty dollars for both nights, breakfast included. Can I take your name and a contact number? Yes, it's Daniel Osei, and my number is oh seven nine, double two five, one one four four. Perfect. And finally, could I get an email address for the confirmation? Yes, it's daniel dot osei, all one word, at fastmail dot com. Great, Mr. Osei, your booking is confirmed for the twelfth and thirteenth of March, Deluxe Lake View room, breakfast included, total three hundred and forty dollars. You'll receive a confirmation email shortly. Thank you very much. You're welcome, we look forward to welcoming you.`,
    questions: [
      { id: 'q1', type: 'short', prompt: 'How many nights is the room booked for?', answer: '2' },
      { id: 'q2', type: 'short', prompt: 'What type of room is booked?', answer: 'Deluxe Lake View' },
      { id: 'q3', type: 'short', prompt: 'What is the total cost, including breakfast?', answer: '$340' },
      { id: 'q4', type: 'short', prompt: "What is the guest's surname?", answer: 'Osei' },
      { id: 'q5', type: 'mcq', prompt: 'What extra item was added to the booking?', options: ['Airport pickup', 'Breakfast', 'Late checkout', 'Parking'], answer: 'Breakfast' },
    ],
  },
  {
    id: 'ls-2',
    section: 1,
    title: 'Joining a Gym',
    type: 'Everyday conversation',
    text: `Hi there, I'm interested in joining the gym. What membership options do you have? We have three plans: Basic, which is pool and gym access only for thirty five dollars a month; Standard, which adds group classes for fifty dollars a month; and Premium, which includes personal training sessions for eighty five dollars a month. I think Standard sounds right for me. Great choice. Standard members get unlimited group classes, including yoga, spin, and boxing. Is there a joining fee? Yes, there's a one-time joining fee of twenty dollars, which is currently waived if you sign up before the end of the month. That's good timing then. It is! Can I take a few details? What's your date of birth? The third of July, nineteen ninety-eight. And do you have any existing injuries we should know about? I had a knee injury last year but it's fully healed now. Noted, we'll have a trainer check in with you during your first session just to be safe. Your membership will start this Monday. Perfect, thank you.`,
    questions: [
      { id: 'q1', type: 'mcq', prompt: 'Which membership plan does the caller choose?', options: ['Basic', 'Standard', 'Premium', 'None'], answer: 'Standard' },
      { id: 'q2', type: 'short', prompt: 'How much does the Standard plan cost per month?', answer: '$50' },
      { id: 'q3', type: 'short', prompt: 'What is the joining fee (before any waiver)?', answer: '$20' },
      { id: 'q4', type: 'short', prompt: 'What past injury does the caller mention?', answer: 'Knee injury' },
      { id: 'q5', type: 'short', prompt: 'When does the membership start?', answer: 'Monday' },
    ],
  },
  {
    id: 'ls-3',
    section: 2,
    title: 'Museum Tour Introduction',
    type: 'Public announcement / monologue',
    text: `Welcome to the City History Museum. Before we begin the tour, let me give you a quick overview of today's route. We'll start on the ground floor in the Ancient Trade gallery, which houses artifacts recovered from the old harbor, including coins and pottery dating back over a thousand years. From there, we'll move upstairs to the Industrial Revolution wing, which explores how the city transformed during the eighteen hundreds. Please note that the elevator to the second floor is currently out of service for maintenance, so we'll be using the staircase near the main entrance. The tour will conclude in the Modern City exhibit on the third floor, where you'll see a scale model of the city as it looks today. Photography is permitted throughout the museum, but please turn off camera flashes, as they can damage some of the older textiles on display. The tour will last approximately ninety minutes, with a short ten-minute break in the museum café roughly halfway through. If at any point you need to step away, the exit signs are clearly marked in green. Restrooms are located on the ground floor, next to the gift shop. Let's begin.`,
    questions: [
      { id: 'q1', type: 'short', prompt: 'Which gallery does the tour start in?', answer: 'Ancient Trade' },
      { id: 'q2', type: 'short', prompt: 'Why is the elevator not being used?', answer: 'Maintenance' },
      { id: 'q3', type: 'short', prompt: 'On which floor is the Modern City exhibit?', answer: 'Third floor' },
      { id: 'q4', type: 'mcq', prompt: 'What must visitors turn off while taking photos?', options: ['Their phones', 'Camera flash', 'Audio guides', 'Bluetooth'], answer: 'Camera flash' },
      { id: 'q5', type: 'short', prompt: 'How long does the whole tour last?', answer: '90 minutes' },
    ],
  },
  {
    id: 'ls-4',
    section: 2,
    title: 'Community Center Program Overview',
    type: 'Public announcement / monologue',
    text: `Thank you for coming to this evening's information session about the new community center programs. Starting next month, we'll be offering four new weekly activities. On Monday evenings, there's a beginner pottery class, running from six to eight p.m., limited to twelve participants. On Wednesday afternoons, we have a gardening club aimed at all ages, which meets in the community garden behind the main building from three to four thirty. Thursday evenings will feature a conversation group for people learning English as a second language, which is completely free of charge, unlike the other programs, which cost fifteen dollars per session. Finally, on Saturday mornings, there will be a youth coding workshop for ages ten to fifteen, running from ten until noon. Registration for all programs opens this Friday through our website, and spaces are expected to fill quickly, particularly for the pottery class. If a class is full, you can join a waiting list, and we'll notify you by email if a spot becomes available. Please note that the community center will be closed for the public holiday on the last Monday of the month, so that week's pottery class will be rescheduled to the following Tuesday.`,
    questions: [
      { id: 'q1', type: 'short', prompt: 'What day does the pottery class run on?', answer: 'Monday' },
      { id: 'q2', type: 'short', prompt: 'Which program is free of charge?', answer: 'Conversation group' },
      { id: 'q3', type: 'short', prompt: 'What is the age range for the coding workshop?', answer: '10 to 15' },
      { id: 'q4', type: 'short', prompt: 'How much do the paid sessions cost?', answer: '$15' },
      { id: 'q5', type: 'mcq', prompt: 'Why will one pottery class be rescheduled?', options: ['Low enrollment', 'A public holiday', 'Instructor unavailable', 'Room maintenance'], answer: 'A public holiday' },
    ],
  },
  {
    id: 'ls-5',
    section: 3,
    title: 'Discussing a Group Assignment',
    type: 'Academic discussion (students)',
    text: `Hey, did you get a chance to look at the assignment brief for our sociology project? Yeah, I read through it. I think we need to pick a specific community to study, right, not just write generally about urbanization. Exactly, and the tutor mentioned we should include at least one interview as primary data. Good point, I'd forgotten about that part. What if we focus on the night market near campus? It's a good example of informal economy and community networks. I like that idea, but we should check if we're allowed to approach vendors directly, some might not want to be interviewed on the record. That's fair, maybe we could offer to keep them anonymous in the write-up. We could also compare it with data from the city council report on informal trading, which covers similar areas. Good, that gives us both primary and secondary sources. Should we split the work by section, or work through the whole thing together? I'd rather split it, honestly, my schedule's tight this week. Okay, how about I handle the interview and background research, and you draft the analysis section once I send you the notes? Sounds fair. Let's aim to have a rough draft by Thursday so we have time to revise before the deadline.`,
    questions: [
      { id: 'q1', type: 'short', prompt: 'What subject is the assignment for?', answer: 'Sociology' },
      { id: 'q2', type: 'short', prompt: 'What real-world location do they choose to study?', answer: 'Night market' },
      { id: 'q3', type: 'mcq', prompt: 'What type of source is the city council report used as?', options: ['Primary source', 'Secondary source', 'Not used', 'Interview data'], answer: 'Secondary source' },
      { id: 'q4', type: 'short', prompt: 'What concern do they raise about interviewing vendors?', answer: 'They might not want to be identified/on the record' },
      { id: 'q5', type: 'short', prompt: 'By what day do they want a rough draft?', answer: 'Thursday' },
    ],
  },
  {
    id: 'ls-6',
    section: 3,
    title: 'Meeting with a Thesis Supervisor',
    type: 'Academic discussion (student & tutor)',
    text: `Come in, please, have a seat. So, you wanted to discuss your thesis structure. Yes, I've drafted an outline, but I'm not sure the literature review is in the right place. Let's take a look. Okay, I see you've put the literature review after your methodology section. Generally, we'd expect the review to come first, since it justifies the research questions you go on to investigate. That makes sense, I think I was worried it would feel repetitive. It's a common worry, but as long as your methodology explicitly references gaps identified in the literature review, it won't feel repetitive, it will feel connected. Should I also include more recent studies? Your most recent citation is from four years ago. Yes, definitely try to include at least a few sources from the last two years, especially since this is a fast-moving field. I'll search the database again this week. Good. Also, your research question is currently quite broad, covering three different age groups. I'd recommend narrowing it to just one group for a project this size. That's helpful, I'll focus on university students specifically then. Great, send me a revised outline by next Friday and we can meet again after that.`,
    questions: [
      { id: 'q1', type: 'mcq', prompt: 'Where does the supervisor recommend placing the literature review?', options: ['After the methodology', 'Before the methodology', 'At the very end', 'It doesn\'t matter'], answer: 'Before the methodology' },
      { id: 'q2', type: 'short', prompt: 'How old is the student\'s most recent citation?', answer: 'Four years' },
      { id: 'q3', type: 'short', prompt: 'How many age groups does the research question currently cover?', answer: 'Three' },
      { id: 'q4', type: 'short', prompt: 'Which single group will the student now focus on?', answer: 'University students' },
      { id: 'q5', type: 'short', prompt: 'By when should the revised outline be sent?', answer: 'Next Friday' },
    ],
  },
  {
    id: 'ls-7',
    section: 4,
    title: 'Lecture: Principles of Urban Planning',
    type: 'Academic lecture',
    text: `Today I want to introduce three core principles that shape modern urban planning. The first is density, which refers to how many people or buildings occupy a given area. Higher density is often associated with more efficient public transport and lower per-person infrastructure costs, but it must be balanced against concerns about overcrowding and green space. The second principle is mixed-use development, meaning that residential, commercial, and recreational spaces are combined within the same neighborhood rather than strictly separated. This reduces the need for long commutes and supports local businesses, since people can shop and work close to home. The third principle is connectivity, which concerns how easily people can move between different parts of a city, whether on foot, by bicycle, or using public transport. Cities with poor connectivity often see heavier reliance on private cars, which increases both traffic congestion and emissions. It's worth noting that these three principles frequently interact: a dense, mixed-use neighborhood with poor connectivity can still function badly, since residents may be unable to reach services efficiently even if those services are nearby. Planners today increasingly use all three principles together, rather than treating density, mixed-use design, and connectivity as separate goals to pursue individually.`,
    questions: [
      { id: 'q1', type: 'short', prompt: 'What is the first principle mentioned in the lecture?', answer: 'Density' },
      { id: 'q2', type: 'mcq', prompt: 'What does mixed-use development combine within one neighborhood?', options: ['Only residential and commercial spaces', 'Residential, commercial, and recreational spaces', 'Only public transport routes', 'Historic and modern buildings'], answer: 'Residential, commercial, and recreational spaces' },
      { id: 'q3', type: 'short', prompt: 'What does poor connectivity often increase reliance on?', answer: 'Private cars' },
      { id: 'q4', type: 'short', prompt: 'What two problems does heavy car reliance increase, according to the lecture?', answer: 'Traffic congestion and emissions' },
      { id: 'q5', type: 'short', prompt: 'How many core principles does the lecturer introduce?', answer: 'Three' },
    ],
  },
  {
    id: 'ls-8',
    section: 4,
    title: 'Lecture: Coral Reef Ecosystems',
    type: 'Academic lecture',
    text: `Coral reefs cover less than one percent of the ocean floor, yet they support roughly a quarter of all known marine species, making them among the most biodiverse ecosystems on the planet. This productivity depends on a delicate partnership between coral polyps, tiny animals that build the reef's calcium carbonate structure, and microscopic algae called zooxanthellae that live inside their tissue. The algae photosynthesize, providing the coral with energy, while the coral provides the algae with a protected environment and access to sunlight. This relationship, however, is highly sensitive to temperature. When water becomes too warm, even by just one or two degrees above the normal seasonal maximum, coral polyps expel their algae in a stress response known as bleaching. Without the algae, the coral loses both its color and its main energy source, and if warm conditions persist for several weeks, the coral can die. Large-scale bleaching events have become more frequent as ocean temperatures rise, with some reef systems losing more than half their coral cover within a single decade. Conservation strategies now include selectively breeding heat-tolerant coral strains and establishing marine protected areas to reduce additional stressors, such as pollution and overfishing, giving reefs a better chance of recovering between heat events.`,
    questions: [
      { id: 'q1', type: 'short', prompt: 'What percentage of marine species do coral reefs support?', answer: 'About a quarter (25%)' },
      { id: 'q2', type: 'mcq', prompt: 'What do zooxanthellae provide to coral?', answer: 'Energy through photosynthesis', options: ['Protection from predators', 'Energy through photosynthesis', 'Calcium carbonate', 'Oxygen only'] },
      { id: 'q3', type: 'short', prompt: 'What is the process called when coral expels its algae?', answer: 'Bleaching' },
      { id: 'q4', type: 'short', prompt: 'What triggers coral bleaching, according to the lecture?', answer: 'Water becoming too warm' },
      { id: 'q5', type: 'short', prompt: 'Name one conservation strategy mentioned.', answer: 'Breeding heat-tolerant coral / marine protected areas' },
    ],
  },
]
