// Seed vocabulary bank: high-utility academic/IELTS words grouped into
// themed sets. Each entry: { id, word, pos, definition, example, synonyms }.
// Used by the Vocabulary module's spaced-repetition flashcards.

export const VOCAB_SETS = [
  {
    id: 'set-education',
    title: 'Education & Learning',
    words: [
      { word: 'curriculum', pos: 'n.', definition: 'the subjects taught by a school or course', example: 'The new curriculum places more emphasis on critical thinking.', synonyms: ['syllabus', 'course of study'] },
      { word: 'vocational', pos: 'adj.', definition: 'relating to skills needed for a particular job', example: 'Vocational training prepares students directly for the workplace.', synonyms: ['occupational', 'practical'] },
      { word: 'pedagogy', pos: 'n.', definition: 'the method and practice of teaching', example: 'Modern pedagogy favors interactive learning over rote memorization.', synonyms: ['teaching method', 'instruction'] },
      { word: 'rote learning', pos: 'n. phr.', definition: 'memorizing through repetition rather than understanding', example: 'Critics argue rote learning discourages independent thought.', synonyms: ['memorization'] },
      { word: 'literacy', pos: 'n.', definition: 'the ability to read and write', example: 'Improving literacy rates remains a priority in developing regions.', synonyms: ['reading ability'] },
      { word: 'proponent', pos: 'n.', definition: 'a person who supports an idea or policy', example: 'Proponents of online learning cite its flexibility.', synonyms: ['advocate', 'supporter'] },
      { word: 'tuition fees', pos: 'n. phr.', definition: 'money paid for instruction, especially at university', example: 'Rising tuition fees have made some students reconsider university.', synonyms: ['school fees'] },
      { word: 'holistic', pos: 'adj.', definition: 'considering the whole person or system, not just one part', example: 'A holistic approach to education includes emotional development.', synonyms: ['comprehensive', 'all-round'] },
      { word: 'underpin', pos: 'v.', definition: 'to form the basis or support for something', example: 'Strong numeracy skills underpin success in the sciences.', synonyms: ['support', 'reinforce'] },
      { word: 'autonomy', pos: 'n.', definition: 'the ability to act independently', example: 'Universities are granting students greater autonomy over their study paths.', synonyms: ['independence', 'self-governance'] },
    ],
  },
  {
    id: 'set-environment',
    title: 'Environment & Sustainability',
    words: [
      { word: 'sustainable', pos: 'adj.', definition: 'able to continue at the same level without harming resources', example: 'Sustainable farming methods protect soil for future generations.', synonyms: ['renewable', 'eco-friendly'] },
      { word: 'depletion', pos: 'n.', definition: 'the reduction of a resource over time', example: 'The depletion of fish stocks has alarmed marine biologists.', synonyms: ['exhaustion', 'reduction'] },
      { word: 'mitigate', pos: 'v.', definition: 'to make something less severe', example: 'Planting trees can help mitigate the effects of flooding.', synonyms: ['alleviate', 'lessen'] },
      { word: 'emissions', pos: 'n.', definition: 'substances released into the air, especially pollutants', example: 'Governments are setting targets to cut carbon emissions.', synonyms: ['discharge', 'output'] },
      { word: 'biodiversity', pos: 'n.', definition: 'the variety of plant and animal life in an area', example: 'Deforestation threatens the region’s biodiversity.', synonyms: ['ecological variety'] },
      { word: 'renewable', pos: 'adj.', definition: 'capable of being replenished naturally', example: 'Solar and wind are examples of renewable energy sources.', synonyms: ['sustainable', 'inexhaustible'] },
      { word: 'conservation', pos: 'n.', definition: 'the protection of natural resources', example: 'Conservation efforts have helped several species recover.', synonyms: ['preservation', 'protection'] },
      { word: 'unprecedented', pos: 'adj.', definition: 'never done or known before', example: 'The region has experienced unprecedented levels of rainfall this year.', synonyms: ['unparalleled', 'record'] },
      { word: 'detrimental', pos: 'adj.', definition: 'causing harm or damage', example: 'Single-use plastics are detrimental to marine ecosystems.', synonyms: ['harmful', 'damaging'] },
      { word: 'curb', pos: 'v.', definition: 'to restrain or limit something', example: 'New regulations aim to curb industrial pollution.', synonyms: ['restrict', 'control'] },
    ],
  },
  {
    id: 'set-technology',
    title: 'Technology & Innovation',
    words: [
      { word: 'automation', pos: 'n.', definition: 'the use of machines to perform tasks automatically', example: 'Automation has transformed manufacturing over the past decade.', synonyms: ['mechanization'] },
      { word: 'ubiquitous', pos: 'adj.', definition: 'present or found everywhere', example: 'Smartphones have become ubiquitous in modern society.', synonyms: ['omnipresent', 'widespread'] },
      { word: 'obsolete', pos: 'adj.', definition: 'no longer used because something newer exists', example: 'Many physical skills are becoming obsolete due to software.', synonyms: ['outdated', 'antiquated'] },
      { word: 'innovation', pos: 'n.', definition: 'a new idea, method, or device', example: 'Innovation in medicine has extended average life expectancy.', synonyms: ['invention', 'advancement'] },
      { word: 'disrupt', pos: 'v.', definition: 'to radically change an established industry or process', example: 'Streaming services have disrupted the traditional television model.', synonyms: ['transform', 'overturn'] },
      { word: 'privacy breach', pos: 'n. phr.', definition: 'an incident where personal data is exposed without consent', example: 'The company faced criticism after a major privacy breach.', synonyms: ['data leak'] },
      { word: 'algorithm', pos: 'n.', definition: 'a set of rules a computer follows to solve a problem', example: 'Social media algorithms determine what content users see.', synonyms: ['formula', 'procedure'] },
      { word: 'artificial intelligence', pos: 'n. phr.', definition: 'computer systems performing tasks that normally require human intelligence', example: 'Artificial intelligence is increasingly used in medical diagnosis.', synonyms: ['AI', 'machine intelligence'] },
      { word: 'streamline', pos: 'v.', definition: 'to make a process more efficient', example: 'The new software streamlines the entire application process.', synonyms: ['simplify', 'optimize'] },
      { word: 'redundant', pos: 'adj.', definition: 'no longer needed, often due to automation', example: 'Thousands of workers were made redundant after the factory was automated.', synonyms: ['superfluous', 'surplus'] },
    ],
  },
  {
    id: 'set-society',
    title: 'Society & Culture',
    words: [
      { word: 'demographic', pos: 'n./adj.', definition: 'relating to the structure of populations', example: 'The country’s demographic is shifting toward an older population.', synonyms: ['population-related'] },
      { word: 'assimilate', pos: 'v.', definition: 'to become part of a different culture or group', example: 'Immigrants often assimilate more easily when they learn the local language.', synonyms: ['integrate', 'adapt'] },
      { word: 'cohesion', pos: 'n.', definition: 'the state of forming a united whole', example: 'Community events help strengthen social cohesion.', synonyms: ['unity', 'solidarity'] },
      { word: 'disparity', pos: 'n.', definition: 'a noticeable difference or inequality', example: 'There is a growing disparity between urban and rural incomes.', synonyms: ['inequality', 'gap'] },
      { word: 'stereotype', pos: 'n.', definition: 'an oversimplified, widely held idea about a group', example: 'The film challenges common stereotypes about rural life.', synonyms: ['generalization', 'cliché'] },
      { word: 'norm', pos: 'n.', definition: 'a standard or expected pattern of behavior', example: 'Remote work has become the norm in many industries.', synonyms: ['standard', 'convention'] },
      { word: 'affluent', pos: 'adj.', definition: 'having a great deal of money; wealthy', example: 'Affluent neighborhoods often have better access to services.', synonyms: ['wealthy', 'prosperous'] },
      { word: 'marginalized', pos: 'adj.', definition: 'treated as insignificant or peripheral by society', example: 'The policy aims to support marginalized communities.', synonyms: ['excluded', 'sidelined'] },
      { word: 'upbringing', pos: 'n.', definition: 'the way a child is cared for and raised', example: 'A person’s upbringing strongly influences their values.', synonyms: ['rearing', 'childhood'] },
      { word: 'generational', pos: 'adj.', definition: 'relating to differences between age groups', example: 'There is a generational divide in attitudes toward social media.', synonyms: ['age-related'] },
    ],
  },
  {
    id: 'set-health',
    title: 'Health & Wellbeing',
    words: [
      { word: 'sedentary', pos: 'adj.', definition: 'characterized by a lot of sitting; little exercise', example: 'A sedentary lifestyle is linked to a higher risk of heart disease.', synonyms: ['inactive'] },
      { word: 'chronic', pos: 'adj.', definition: 'persisting for a long time', example: 'Chronic illnesses require long-term management rather than a quick cure.', synonyms: ['persistent', 'long-term'] },
      { word: 'malnutrition', pos: 'n.', definition: 'lack of proper nutrition', example: 'Malnutrition remains a serious problem in several regions.', synonyms: ['undernourishment'] },
      { word: 'epidemic', pos: 'n.', definition: 'a widespread occurrence of a disease in a population', example: 'Obesity has been described as a modern epidemic.', synonyms: ['outbreak'] },
      { word: 'well-being', pos: 'n.', definition: 'the state of being comfortable, healthy, or happy', example: 'Employers are paying closer attention to staff well-being.', synonyms: ['welfare', 'health'] },
      { word: 'preventive', pos: 'adj.', definition: 'intended to stop something from happening', example: 'Preventive healthcare reduces long-term costs for the system.', synonyms: ['precautionary'] },
      { word: 'stigma', pos: 'n.', definition: 'a mark of disgrace associated with a particular circumstance', example: 'There is still stigma attached to discussing mental health.', synonyms: ['shame', 'disgrace'] },
      { word: 'burnout', pos: 'n.', definition: 'physical or mental collapse from overwork or stress', example: 'Long hours without breaks often lead to burnout.', synonyms: ['exhaustion'] },
      { word: 'resilience', pos: 'n.', definition: 'the capacity to recover quickly from difficulties', example: 'Building resilience helps individuals cope with setbacks.', synonyms: ['toughness', 'adaptability'] },
      { word: 'accessible', pos: 'adj.', definition: 'able to be reached or obtained easily', example: 'Affordable healthcare should be accessible to everyone.', synonyms: ['available', 'attainable'] },
    ],
  },
  {
    id: 'set-economy',
    title: 'Economy & Work',
    words: [
      { word: 'recession', pos: 'n.', definition: 'a period of temporary economic decline', example: 'The country entered a recession after two quarters of negative growth.', synonyms: ['downturn', 'slump'] },
      { word: 'subsidy', pos: 'n.', definition: 'money given by government to support an industry', example: 'Farmers rely on government subsidies during poor harvests.', synonyms: ['grant', 'financial aid'] },
      { word: 'workforce', pos: 'n.', definition: 'all the people who work in a country or company', example: 'The aging workforce poses challenges for pension systems.', synonyms: ['labor force'] },
      { word: 'outsource', pos: 'v.', definition: 'to obtain services from an outside supplier', example: 'Many firms outsource customer service to reduce costs.', synonyms: ['contract out'] },
      { word: 'commodity', pos: 'n.', definition: 'a raw material or primary product that can be bought and sold', example: 'Oil remains one of the world’s most traded commodities.', synonyms: ['goods', 'product'] },
      { word: 'entrepreneur', pos: 'n.', definition: 'a person who starts and runs a business, taking on risk', example: 'Young entrepreneurs are driving growth in the tech sector.', synonyms: ['business owner', 'founder'] },
      { word: 'inflation', pos: 'n.', definition: 'a general rise in prices over time', example: 'Rising inflation has reduced households’ purchasing power.', synonyms: ['price rise'] },
      { word: 'incentive', pos: 'n.', definition: 'something that motivates a particular action', example: 'Tax incentives encourage companies to invest in renewable energy.', synonyms: ['motivation', 'inducement'] },
      { word: 'downsize', pos: 'v.', definition: 'to reduce the size of a company’s workforce', example: 'The firm was forced to downsize after losing its main client.', synonyms: ['cut back', 'lay off staff'] },
      { word: 'viable', pos: 'adj.', definition: 'capable of working successfully', example: 'Remote work has proven a viable alternative to commuting.', synonyms: ['feasible', 'workable'] },
    ],
  },
  {
    id: 'set-crime',
    title: 'Crime & Law',
    words: [
      { word: 'deter', pos: 'v.', definition: 'to discourage someone from doing something', example: 'Harsher penalties are intended to deter repeat offenders.', synonyms: ['discourage', 'dissuade'] },
      { word: 'rehabilitation', pos: 'n.', definition: 'the process of restoring someone to a normal life after wrongdoing', example: 'Prison programs focused on rehabilitation reduce reoffending rates.', synonyms: ['reform', 'recovery'] },
      { word: 'legislation', pos: 'n.', definition: 'laws considered collectively', example: 'New legislation was passed to tighten data protection.', synonyms: ['law', 'statute'] },
      { word: 'enforce', pos: 'v.', definition: 'to compel observance of a law or rule', example: 'Local authorities struggle to enforce parking regulations.', synonyms: ['implement', 'apply'] },
      { word: 'surveillance', pos: 'n.', definition: 'close observation, especially of a suspected person', example: 'The city has expanded its use of public surveillance cameras.', synonyms: ['monitoring', 'observation'] },
      { word: 'juvenile', pos: 'adj./n.', definition: 'relating to young people, especially offenders', example: 'Juvenile crime rates have fallen over the past decade.', synonyms: ['youth', 'young'] },
      { word: 'deterrent', pos: 'n.', definition: 'something that discourages an action', example: 'Some argue the death penalty is not an effective deterrent.', synonyms: ['disincentive'] },
      { word: 'infringe', pos: 'v.', definition: 'to break a law or violate a right', example: 'The policy has been criticized for infringing on privacy rights.', synonyms: ['violate', 'breach'] },
      { word: 'sentence', pos: 'n./v.', definition: 'the punishment given by a court', example: 'The judge handed down a lengthy sentence.', synonyms: ['punishment', 'verdict'] },
      { word: 'petty crime', pos: 'n. phr.', definition: 'minor offenses such as small thefts', example: 'Petty crime tends to rise during periods of economic hardship.', synonyms: ['minor offense'] },
    ],
  },
  {
    id: 'set-globalization',
    title: 'Globalization & Travel',
    words: [
      { word: 'globalization', pos: 'n.', definition: 'the process by which businesses and cultures become interconnected worldwide', example: 'Globalization has made it easier to access foreign products.', synonyms: ['internationalization'] },
      { word: 'homogenize', pos: 'v.', definition: 'to make uniform or similar', example: 'Critics worry that global chains homogenize local culture.', synonyms: ['standardize'] },
      { word: 'tourism', pos: 'n.', definition: 'travel for pleasure or business', example: 'Tourism accounts for a significant share of the country’s income.', synonyms: ['travel industry'] },
      { word: 'infrastructure', pos: 'n.', definition: 'the basic physical systems of a country (roads, power, etc.)', example: 'Investment in infrastructure has improved rural connectivity.', synonyms: ['facilities', 'foundation'] },
      { word: 'diaspora', pos: 'n.', definition: 'people who have spread from an original homeland', example: 'The diaspora sends significant remittances back home.', synonyms: ['dispersed community'] },
      { word: 'export', pos: 'v./n.', definition: 'to sell goods to another country', example: 'The nation exports most of its agricultural produce.', synonyms: ['ship abroad'] },
      { word: 'interdependence', pos: 'n.', definition: 'mutual reliance between countries or groups', example: 'Global supply chains have increased economic interdependence.', synonyms: ['mutual dependence'] },
      { word: 'multinational', pos: 'adj.', definition: 'operating in several countries', example: 'Multinational corporations often relocate factories to cut costs.', synonyms: ['transnational'] },
      { word: 'remittance', pos: 'n.', definition: 'money sent, typically by a worker abroad, back home', example: 'Remittances form a large part of the country’s GDP.', synonyms: ['money transfer'] },
      { word: 'itinerary', pos: 'n.', definition: 'a planned route or schedule for a journey', example: 'She planned a detailed itinerary before the trip.', synonyms: ['travel plan', 'schedule'] },
    ],
  },
  {
    id: 'set-government',
    title: 'Government & Policy',
    words: [
      { word: 'regulation', pos: 'n.', definition: 'a rule made by an authority', example: 'Stricter regulation has reduced workplace accidents.', synonyms: ['rule', 'directive'] },
      { word: 'welfare', pos: 'n.', definition: 'statutory support provided to those in need', example: 'The welfare system provides a safety net for the unemployed.', synonyms: ['social support'] },
      { word: 'allocate', pos: 'v.', definition: 'to distribute resources for a particular purpose', example: 'The budget allocates more funding to public transport this year.', synonyms: ['assign', 'distribute'] },
      { word: 'accountable', pos: 'adj.', definition: 'required to justify actions or decisions', example: 'Officials should be held accountable for how public funds are spent.', synonyms: ['answerable', 'responsible'] },
      { word: 'referendum', pos: 'n.', definition: 'a direct public vote on a specific issue', example: 'The country held a referendum on the proposed reform.', synonyms: ['public vote'] },
      { word: 'bureaucracy', pos: 'n.', definition: 'a system of administration marked by complex procedures', example: 'Excessive bureaucracy can slow down small business registration.', synonyms: ['red tape', 'administration'] },
      { word: 'transparency', pos: 'n.', definition: 'operating in a way that is easy to see and verify', example: 'Greater transparency in spending builds public trust.', synonyms: ['openness'] },
      { word: 'levy', pos: 'v./n.', definition: 'to impose a tax or fee', example: 'The government plans to levy a new tax on sugary drinks.', synonyms: ['impose', 'charge'] },
      { word: 'constituency', pos: 'n.', definition: 'a group of voters in a specific area', example: 'The candidate focused her campaign on a single constituency.', synonyms: ['electorate'] },
      { word: 'stakeholder', pos: 'n.', definition: 'a person with an interest or concern in something', example: 'All stakeholders were consulted before the policy was finalized.', synonyms: ['interested party'] },
    ],
  },
  {
    id: 'set-media',
    title: 'Media & Communication',
    words: [
      { word: 'misinformation', pos: 'n.', definition: 'false or inaccurate information spread regardless of intent', example: 'Misinformation spreads rapidly on social media platforms.', synonyms: ['false information'] },
      { word: 'censorship', pos: 'n.', definition: 'the suppression of speech or information', example: 'Journalists in some countries operate under strict censorship.', synonyms: ['suppression'] },
      { word: 'bias', pos: 'n.', definition: 'a tendency to favor one perspective unfairly', example: 'Readers should be aware of potential bias in news reporting.', synonyms: ['prejudice', 'partiality'] },
      { word: 'credible', pos: 'adj.', definition: 'able to be believed; trustworthy', example: 'It is important to rely on credible sources of information.', synonyms: ['trustworthy', 'reliable'] },
      { word: 'sensationalism', pos: 'n.', definition: 'presenting news in a shocking way to provoke interest', example: 'Some outlets are criticized for prioritizing sensationalism over accuracy.', synonyms: ['exaggeration'] },
      { word: 'platform', pos: 'n.', definition: 'a system or service, often online, for sharing content', example: 'Video platforms have changed how people consume entertainment.', synonyms: ['medium', 'service'] },
      { word: 'discourse', pos: 'n.', definition: 'communication in speech or writing about a topic', example: 'Public discourse around privacy has intensified in recent years.', synonyms: ['debate', 'discussion'] },
      { word: 'anonymity', pos: 'n.', definition: 'the state of being unknown or unnamed', example: 'Online anonymity can encourage both honesty and abuse.', synonyms: ['namelessness'] },
      { word: 'proliferation', pos: 'n.', definition: 'rapid increase in the number or amount of something', example: 'The proliferation of streaming services has fragmented audiences.', synonyms: ['spread', 'growth'] },
      { word: 'scrutiny', pos: 'n.', definition: 'critical observation or examination', example: 'Public figures face constant scrutiny from the press.', synonyms: ['examination', 'inspection'] },
    ],
  },
  {
    id: 'set-band9-verbs',
    title: 'Band 9: Precise Academic Verbs',
    words: [
      { word: 'underscore', pos: 'v.', definition: 'to emphasise or highlight the importance of something', example: 'The report underscores the need for urgent reform.', synonyms: ['emphasise', 'highlight'] },
      { word: 'conflate', pos: 'v.', definition: 'to wrongly treat two distinct things as if they were one', example: 'Critics argue the policy conflates correlation with causation.', synonyms: ['merge', 'blur together'] },
      { word: 'circumvent', pos: 'v.', definition: 'to find a way around an obstacle or rule', example: 'Some firms restructure specifically to circumvent the new tax.', synonyms: ['bypass', 'evade'] },
      { word: 'exacerbate', pos: 'v.', definition: 'to make a problem worse', example: 'Cutting funding further would only exacerbate the shortage.', synonyms: ['worsen', 'aggravate'] },
      { word: 'corroborate', pos: 'v.', definition: 'to confirm or support with additional evidence', example: 'Independent data corroborate the study\'s central finding.', synonyms: ['confirm', 'substantiate'] },
      { word: 'delineate', pos: 'v.', definition: 'to describe or outline precisely', example: 'The contract delineates each party\'s responsibilities in detail.', synonyms: ['outline', 'define clearly'] },
      { word: 'eschew', pos: 'v.', definition: 'to deliberately avoid something', example: 'The designer eschews ornamentation in favour of stark simplicity.', synonyms: ['avoid', 'shun'] },
      { word: 'galvanise', pos: 'v.', definition: 'to prompt someone into sudden, decisive action', example: 'The images galvanised public support for the campaign.', synonyms: ['spur', 'mobilise'] },
      { word: 'preclude', pos: 'v.', definition: 'to prevent something from happening', example: 'A prior commitment precluded her from attending.', synonyms: ['prevent', 'rule out'] },
      { word: 'substantiate', pos: 'v.', definition: 'to provide evidence to support a claim', example: 'The claim has yet to be substantiated by peer-reviewed research.', synonyms: ['verify', 'prove'] },
      { word: 'undermine', pos: 'v.', definition: 'to weaken or damage something gradually', example: 'Persistent delays have undermined public confidence in the project.', synonyms: ['weaken', 'erode'] },
      { word: 'reconcile', pos: 'v.', definition: 'to make two seemingly conflicting things compatible', example: 'The report attempts to reconcile growth targets with environmental limits.', synonyms: ['harmonise', 'square'] },
    ],
  },
  {
    id: 'set-band9-collocations',
    title: 'Band 9: Natural Collocations & Idiom',
    words: [
      { word: 'a far cry from', pos: 'idiom', definition: 'very different from something', example: 'The final policy is a far cry from what was originally proposed.', synonyms: ['nothing like', 'worlds apart from'] },
      { word: 'strike a balance', pos: 'collocation', definition: 'to find a satisfactory middle point between two demands', example: 'Regulators must strike a balance between innovation and consumer protection.', synonyms: ['find equilibrium'] },
      { word: 'a double-edged sword', pos: 'idiom', definition: 'something with both significant benefits and significant drawbacks', example: 'Automation is a double-edged sword for the manufacturing workforce.', synonyms: ['mixed blessing'] },
      { word: 'gain traction', pos: 'collocation', definition: 'to start to become accepted or popular', example: 'The four-day work week is gaining traction among tech firms.', synonyms: ['gain momentum', 'catch on'] },
      { word: 'a slippery slope', pos: 'idiom', definition: 'a course of action likely to lead to a worse, harder-to-reverse outcome', example: 'Opponents warn the exemption is a slippery slope toward broader deregulation.', synonyms: ['a dangerous precedent'] },
      { word: 'the elephant in the room', pos: 'idiom', definition: 'an obvious problem that people avoid discussing', example: 'Funding was the elephant in the room throughout the negotiations.', synonyms: ['the unspoken issue'] },
      { word: 'cut corners', pos: 'idiom', definition: 'to do something in the cheapest or easiest way, often sacrificing quality', example: 'Investigators found the contractor had cut corners on safety inspections.', synonyms: ['skimp', 'take shortcuts'] },
      { word: 'a watershed moment', pos: 'idiom', definition: 'a turning point after which things are markedly different', example: 'The ruling was a watershed moment for digital privacy law.', synonyms: ['a turning point', 'a landmark event'] },
      { word: 'at the mercy of', pos: 'idiom', definition: 'entirely dependent on and unable to resist something', example: 'Coastal farmers remain at the mercy of increasingly erratic weather.', synonyms: ['vulnerable to', 'subject to'] },
      { word: 'a stopgap measure', pos: 'collocation', definition: 'a temporary solution used until a permanent one is found', example: 'The subsidy was intended as a stopgap measure, not a long-term fix.', synonyms: ['a temporary fix', 'a band-aid solution'] },
      { word: 'far-reaching implications', pos: 'collocation', definition: 'consequences that extend widely, often unpredictably', example: 'The court\'s decision could have far-reaching implications for the industry.', synonyms: ['wide-ranging consequences'] },
      { word: 'in the same vein', pos: 'idiom', definition: 'following the same style or pattern as something just mentioned', example: 'In the same vein, critics question whether the second reform will fare any better.', synonyms: ['similarly', 'along the same lines'] },
    ],
  },
]

export const ALL_VOCAB_WORDS = VOCAB_SETS.flatMap((set) =>
  set.words.map((w, i) => ({ ...w, id: `${set.id}-${i}`, setId: set.id, setTitle: set.title }))
)
