// Original writing prompts. Academic Task 1 prompts include chart data so
// the app can render the visual with Recharts, just like the real test.

export const WRITING_PROMPTS = [
  {
    id: 'wp-ac-t1-1',
    module: 'academic',
    task: 'task1',
    title: 'Internet Usage by Age Group',
    prompt: 'The line graph below shows the percentage of internet users by age group in one country between 2015 and 2025. Summarize the information by selecting and reporting the main features, and make comparisons where relevant.',
    guidance: [
      'Write an overview first: identify the 1-2 biggest overall trends before any detail.',
      'Group data logically (e.g. by age group or by time period) rather than describing every point in order.',
      'Use a range of comparison language: "whereas", "in contrast", "a similar pattern".',
    ],
    targetWords: 150,
    targetMinutes: 20,
    chart: {
      type: 'line',
      xKey: 'year',
      data: [
        { year: 2015, '16-24': 88, '25-44': 74, '45-64': 45, '65+': 12 },
        { year: 2018, '16-24': 93, '25-44': 82, '45-64': 58, '65+': 20 },
        { year: 2021, '16-24': 96, '25-44': 89, '45-64': 70, '65+': 34 },
        { year: 2025, '16-24': 98, '25-44': 94, '45-64': 81, '65+': 52 },
      ],
      series: ['16-24', '25-44', '45-64', '65+'],
      unit: '%',
    },
  },
  {
    id: 'wp-ac-t1-2',
    module: 'academic',
    task: 'task1',
    title: 'Household Energy Consumption by Source',
    prompt: 'The chart below shows household energy consumption by source in 2020 and 2025 (in petajoules). Summarize the information by selecting and reporting the main features, and make comparisons where relevant.',
    guidance: [
      'Highlight the clearest change between the two years first (the overview).',
      'Don\'t just list six numbers — group sources that rose together vs. fell together.',
      'Round figures sensibly in your summary rather than repeating every exact number.',
    ],
    targetWords: 150,
    targetMinutes: 20,
    chart: {
      type: 'bar',
      xKey: 'source',
      data: [
        { source: 'Natural gas', '2020': 420, '2025': 340 },
        { source: 'Electricity (grid)', '2020': 310, '2025': 280 },
        { source: 'Solar (rooftop)', '2020': 40, '2025': 165 },
        { source: 'Heating oil', '2020': 180, '2025': 95 },
        { source: 'Wood/biomass', '2020': 60, '2025': 55 },
      ],
      series: ['2020', '2025'],
      unit: 'PJ',
    },
  },
  {
    id: 'wp-ac-t2-1',
    module: 'academic',
    task: 'task2',
    title: 'Vocational vs. Academic Education',
    prompt: 'Some people believe universities should focus primarily on academic subjects, while others think they should prioritize practical, vocational skills that directly prepare students for employment. Discuss both views and give your own opinion.',
    guidance: [
      'Give roughly equal space to both views before stating your own opinion clearly.',
      'Use specific examples (a field of study, a country\'s policy) rather than only general claims.',
      'Make sure your conclusion matches the position argued in your body paragraphs.',
    ],
    targetWords: 250,
    targetMinutes: 40,
  },
  {
    id: 'wp-ac-t2-2',
    module: 'academic',
    task: 'task2',
    title: 'Public Transport vs. Roads',
    prompt: 'Governments should invest more money in public transport systems than in building new roads. To what extent do you agree or disagree?',
    guidance: [
      'This is an opinion essay — take a clear position in the introduction and keep it consistent.',
      'Consider counterarguments briefly, but don\'t let them dominate the essay if you disagree with them.',
      'Use precise topic vocabulary: "congestion", "emissions", "infrastructure", "commuters".',
    ],
    targetWords: 250,
    targetMinutes: 40,
  },
  {
    id: 'wp-gt-t1-1',
    module: 'general',
    task: 'task1',
    title: 'Letter to a Landlord',
    prompt: 'You are renting an apartment and there is a persistent problem with the heating system. Write a letter to your landlord. In your letter: describe the problem, explain how it is affecting you, and say what action you would like the landlord to take.',
    guidance: [
      'This should be a formal letter — use "Dear Mr/Ms [Surname]" and a formal closing.',
      'Cover all three bullet points; each usually needs its own short paragraph.',
      'State clearly what outcome you want, not just what\'s wrong.',
    ],
    targetWords: 150,
    targetMinutes: 20,
  },
  {
    id: 'wp-gt-t1-2',
    module: 'general',
    task: 'task1',
    title: 'Letter to a Friend About Moving Abroad',
    prompt: 'You have recently moved to a new country for work. Write a letter to a friend back home. In your letter: explain why you moved, describe your first impressions of the new country, and invite them to visit.',
    guidance: [
      'This is informal — a friendly opening and closing are appropriate.',
      'Keep a warm, personal tone while still covering all three bullet points.',
      'A specific, vivid detail (a place, a food, a habit) makes the letter feel authentic.',
    ],
    targetWords: 150,
    targetMinutes: 20,
  },
  {
    id: 'wp-gt-t2-1',
    module: 'general',
    task: 'task2',
    title: 'Technology and Family Time',
    prompt: 'Many people believe that smartphones and other devices have reduced the amount of quality time families spend together. To what extent do you agree with this view?',
    guidance: [
      'General Training Task 2 essays are scored the same way as Academic — don\'t treat it as less formal.',
      'Balance personal examples with a clear line of argument.',
      'A short, focused conclusion that restates your position works well.',
    ],
    targetWords: 250,
    targetMinutes: 40,
  },
  {
    id: 'wp-gt-t2-2',
    module: 'general',
    task: 'task2',
    title: 'Working from Home',
    prompt: 'Some people think that working from home benefits both employees and employers, while others believe it creates more problems than it solves. Discuss both views and give your own opinion.',
    guidance: [
      'Bring in both perspectives (productivity, isolation, cost savings, communication difficulty).',
      'Use linking devices to signal contrast clearly: "on the other hand", "conversely".',
      'End with a clear, brief statement of your own view.',
    ],
    targetWords: 250,
    targetMinutes: 40,
  },
]
